### ISSUE TITLE
[Open] Larger than standard launcher icons in Arch Linux Rolling V20.1

### ISSUE THREAD

**Issue by serial02** [felixonmars/dde-launcher#1]
Hello Deepin-Launcher Team

After deepin-launcher-5.3.0.35-1 update, some launcher icons were larger than the default. More specifically, the icons AV Eset and hplip.

![Captura de Tela_Opera_20210104152510](https://user-images.githubusercontent.com/32621790/103589628-9976eb80-4eca-11eb-9627-43a81ffc6c27.png)

![Captura de Tela_select-area_20210104185910](https://user-images.githubusercontent.com/32621790/103589673-b14e6f80-4eca-11eb-9dbd-3343a42cc2dd.png)

![Captura de Tela_select-area_20210104190835](https://user-images.githubusercontent.com/32621790/103589762-e78bef00-4eca-11eb-803d-e9a7deb14e91.png)

![Captura de Tela_select-area_20210104202425](https://user-images.githubusercontent.com/32621790/103589778-f2df1a80-4eca-11eb-83f7-ce85fdf8caa6.png)

**Comment by felixonmars** [comment]
This is not the upstream repository. Please report to https://github.com/linuxdeepin/dde-launcher
